### ISSUE TITLE
Conf using vhost SetEnv not working

### ISSUE THREAD

**Issue by GuillaumeSeren** [propelorm/Propel2#1150]
Hey,
I am using propel on a project with docker, as I need to push it to test server, 
I find the suggested way to configure it is using environment variable → http://propelorm.org/documentation/10-configuration.html

So I added my conf in my vhost, like:
``` apache
SetEnv DB_HOST 172.17.0.1
SetEnv DB_USER root
SetEnv DB_PASS password
SetEnv DB_PORT 3306
SetEnv DB_NAME db_name
```

I works well by http, but if I use the propel command line tool, I got an error
``` php
[Propel\Common\Config\Exception\InvalidArgumentException]  
  Environment variable 'db_host' is not defined.
```
I think that come because my vhost is only called by http query, but what do you suggest to keep the command line functionnal ?

**Comment by GuillaumeSeren** [comment]
I think I find the way just after posting the issue,
I put the common conf in propel.yml.dist and use propel.yml,
to locally override value.

I guess it is the benefit of writing it down !

**Comment by GuillaumeSeren** [comment]
After testing,
I think there might be a issue anyway in that case, because I still get the http connection working but the cmd fail with this error (the cmd is done in a container, and it worked well before using en).
```php
[Propel\Common\Config\Exception\InvalidArgumentException]  
Environment variable 'db_host' is not defined.
```
My apache env
```apache
setenv db_host 172.17.0.1
setenv db_user root
setenv db_pass password
setenv db_port 3306
setenv db_name dbname
```
My propel.yml.dist
```yml
database:
    connections:
        default:
            adapter: mysql
            dsn: mysql:host=%env.db_host%;port=%env.db_port%;dbname=%env.db_name%
            user: %env.db_user%
            password: %env.mysql_pass%
            settings:
                charset: utf8
```
My propel.yml
```yml
propel:
    database:
        connections:
            default:
                adapter: mysql
                dsn: mysql:host=172.17.0.1;port=3306;dbname=dbname
                user: root
                password: password
                settings:
                    charset: utf8
```

It seem's that the overriding is not working on the shell tool ?

**Comment by GuillaumeSeren** [comment]
So I investigate a bit more and I don't think there is a bug in the loader,
but the error is not really clear in that case, so I changed the '.dist' configuration from
```yml
database:
    connections:
        default:
            adapter: mysql
            dsn: mysql:host=%env.db_host%;port=%env.db_port%;dbname=%env.db_name%
            user: %env.db_user%
            password: %env.mysql_pass%
            settings:
                charset: utf8
```
to
```yml
propel:
    database:
        default:
            adapter: mysql
            dsn: mysql:host=%env.db_host%;port=%env.db_port%;dbname=%env.db_name%
            user: %env.db_user%
            password: %env.mysql_pass%
            settings:
                charset: utf8
```

So apparently this comes from the 'connections' part, maybe I missed something in the doc, but I think it could be a better validation/error on the '.dist' config, I will check if I find something to hack on that part.
