### ISSUE TITLE
Problem Using Namespaces As A Directory Structure

### ISSUE THREAD

**Issue by ferfujikawa** [propelorm/Propel2#1166]
Hello.

I'm using Propel 2 and trying to generate model classes in subdirectories without repeating the namespace property on each table tag based on table's schema name (see [How to Use Namespaces](http://propelorm.org/documentation/cookbook/namespaces.html) section Using Namespaces As A Directory Structure).

Here is my propel.yml:

```
propel:
    database:
        connections:
            default:
                adapter: pgsql
                dsn: pgsql:host=localhost;port=5432;dbname=database
                user: user
                password: password
                settings:
                    charset: utf8
    generator:
        schema:
            autoPackage: true
```

But, when I execute the command `propel model:build` the classes are been generated in the root folder instead of been generated in subdirectories.

Am I doing something wrong?
