### ISSUE TITLE
Reverse engeneering using custom parserClass

### ISSUE THREAD

**Issue by ferfujikawa** [propelorm/Propel2#1167]
Hi.

I need to generate model classes from a large number of tables in my database, keeping combination between schema (pgsql) and namespace (php).

I've tried using the autopackage option but it did not work (#1166).

Then, my workaround was to generate a schema.xml file where the namespace attribute had the same value of schema attribute.

To do not do it manually I needed to change the class [PgsqlSchemaParser.php](https://github.com/propelorm/Propel2/blob/master/src/Propel/Generator/Reverse/PgsqlSchemaParser.php) at line 189 adding `$table->setNamespace($namespaceName);`. It worked but I think it's not the best solution.

Before, I've tried to extend this class and use the classParser option for reverse command in the propel.yml, but also it didn't work.

Is there another way to do this?

**Comment by marcj** [comment]
You can use your own parser, when you use the correct configuration option :P It's called `parserClass`, not classParser.

Example:

```yml
propel:
  database:
      connections:
          default:
              adapter: mysql
              dsn: mysql:host=localhost;dbname=test
              user: root
              password: superpw
  migrations:
    parserClass: MJS\MyParser
```

http://propelorm.org/documentation/reference/configuration-file.html#migrations-settings
