### ISSUE TITLE
Different connections for Generator and Runtime

### ISSUE THREAD

**Issue by anthropos9** [propelorm/Propel2#1427]
I'm using Docker to develop an app with Propel2. I have a connection that my docker container uses and a second connection that my local machine uses when I run vendor/bin/propel. For some reason these two connections are not playing nice.

This is my configuration:
```
propel:
    database:
        connections:
            default:
                adapter: mysql
                dsn: mysql:host=percona;port=3306;dbname=gb2
                user: root
                password: ---
                settings:
                    charset: utf8
            gen:
                adapter: mysql
                dsn: mysql:host=127.0.0.1;port=8306;dbname=gb2
                user: root
                password: ---
                settings:
                    charset: utf8
    runtime:
      defaultConnection: default
      connections:
          - default
    generator:
      namespaceAutoPackage: false
      defaultConnection: gen
      connections:
          - gen
```

And this is my generated config.php file:
```
<?php
$serviceContainer = \Propel\Runtime\Propel::getServiceContainer();
$serviceContainer->checkVersion('2.0.0-dev');
$serviceContainer->setAdapterClass('default', 'mysql');
$manager = new \Propel\Runtime\Connection\ConnectionManagerSingle();
$manager->setConfiguration(array (
  'dsn' => 'mysql:host=percona;port=3306;dbname=gb2',
  'user' => 'root',
  'password' => '---',
  'settings' =>
  array (
    'charset' => 'utf8',
    'queries' =>
    array (
    ),
  ),
  'classname' => '\\Propel\\Runtime\\Connection\\ConnectionWrapper',
  'model_paths' =>
  array (
    0 => 'src',
    1 => 'vendor',
  ),
));
$manager->setName('default');
$serviceContainer->setConnectionManager('default', $manager);
$serviceContainer->setDefaultDatasource('default');
```
Schema looks like this:
```
<database name="gen" defaultIdMethod="native" namespace="Gearbox\Model" defaultPhpNamingMethod="underscore">
...
</database>
```

And this is the error I'm receiving
```
Fatal error: Uncaught Propel\Runtime\Exception\RuntimeException: No connection defined for database "gen". Did you forget to define a connection or is it wrong written? in /var/www/gb2/vendor/propel/propel/src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php on line 279
```

Any help would be welcomed. Thanks.
