### ISSUE TITLE
Postgres 12 [Travis-CI] [Easy]

### ISSUE THREAD

**Issue by Incognito** [propelorm/Propel2#1569]
Related to: https://github.com/propelorm/Propel2/issues/1541

Travis-ci fails to install postgres 12, it looks like travis has some invalid configuration on their end. It should be possible to manually install via apt. Eg: https://github.com/spryker-shop/suite/blob/master/.travis.yml#L181

**Comment by Incognito** [comment]
Tried to set it manually:

```
    - php: 7.3
      env: DB=pgsql POSTGRES=12 PGPORT=5433
      addons:
        postgresql: 12
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      install:
        - sudo sed -i 's/md5/trust/g' /etc/postgresql/12/main/pg_hba.conf
        - sudo sed -i 's/peer/trust/g' /etc/postgresql/12/main/pg_hba.conf
        - sudo pg_ctlcluster --skip-systemctl-redirect 12 main restart
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - composer install -v
        - composer show
```

Tests fail on travis (exit 255) but not docker.

No error message, needs more debugging. I suspect it's related to a file-open in the `/tmp` dir.
