### ISSUE TITLE
PRIO: Move to GitHub actions

### ISSUE THREAD

**Issue by dereuromark** [propelorm/Propel2#1668]
Since Travis is not supporting FOSS anymore really, we would need to use
now GitHub Actions for example.

Example of PHP with sqlite, mysql, postgres and prefer lowest:
https://github.com/FriendsOfCake/search/pull/299

Anyone wants to try doing this?
That would be awesome.

We can also do only parts of the current test matrix and incrementally improve it.

**Comment by dereuromark** [comment]
Please note:
Right now CI runs already take many hours per commit.

If anyone wans to give this a go, see also https://github.com/cakephp/cakephp/blob/master/.github/workflows/ci.yml for helpful reference on ORM testing/setup.

**Comment by cristianoc72** [comment]
I'm working on this issue and I have a question to discuss.
A possible build matrix to cover all dbms, php and Symfony components versions could be the following:

```yaml
matrix:
                php-version: ['7.2', '7.4']
                db-type: [sqlite, mysql, pgsql, agnostic]
                postgres-version: [ '9.5', '9.6', '10', '11', '12' ]
                mariadb-version: [ '10.1', '10.2', '10.3', '10.4' ]
                symfony-version: ['3-min', '3-max', '4-min', '4-max', '5-min', '5-max']
                exclude:
                    - db-type: sqlite
                      postgres-version: [ '9.5', '9.6', '10', '11', '12' ]
                      mariadb-version: [ '10.1', '10.2', '10.3', '10.4' ]
                    - db-type: mysql
                      postgres-version: [ '9.5', '9.6', '10', '11', '12' ]
                    - db-type: pgsql
                      mariadb-version: [ '10.1', '10.2', '10.3', '10.4' ]
                    - db-type: agnostic
                      postgres-version: [ '9.5', '9.6', '10', '11', '12' ]
                      mariadb-version: [ '10.1', '10.2', '10.3', '10.4' ]
```
Unfortunately, it exceeds the limit of 256 jobs (the `exclude` section is computed after this check) and the workflow fails.
I can see 2 possible solutions:

1.  Reduce the versions to test against (i.e only Postgres 11 and 12 and only Maria 10.4)
2.  Split the workflow in dbms separated workflows (i.e instead of `tests.yml` we could have `tests.pgsql.yml`, `test.sqlite.yml`).

I also tried to use the `include` option, to add the dbms versions later:

```yml
matrix:
                php-version: ['7.2', '7.4']
                db-type: [sqlite, mysql, pgsql, agnostic]
                symfony-version: ['3-min', '3-max', '4-min', '4-max', '5-min', '5-max']
                include:
                    - db-type: mysql
                      mariadb-version: [ '10.1', '10.2', '10.3', '10.4' ]
                    - db-type: pgsql
                      postgres-version: [ '9.5', '9.6', '10', '11', '12' ]
```
But it's not allowed to add arrays on the fly so the setup of pgsl and mysql failed.

Any suggestion?
