### ISSUE TITLE
Custom initial queries are not executed since config refactor

### ISSUE THREAD

**Issue by dhm80** [propelorm/Propel2#669]
With #527 a new config handling was introduced. Nice work! But unfortunately there is a bug in your structure:

In order to run custom initial queries when the database connection is initialized, the generated `config.php` (built via `propel config:convert`) expects an array structure like this:

``` php
$manager->setConfiguration(array(
  ## other key => value pairs,
  'settings' => array (
    'charset' => 'utf8',
    'queries' => array(
      'query' => array (
        'utf8' => 'sql query goes here',
      ),
    ),
  ),
));
```

But the `propel.yaml` expects:

```
propel:
  database:
    connections:
      default:
        settings:
          charset: utf8
          query:
            - "sql query goes here"
```

So the level `queries` between `settings` and `query` is missing. 

Please fix! Thanks ;)
