### ISSUE TITLE
[Config] Make runtime.connections and generator.connections as optional

### ISSUE THREAD

**Issue by cristianoc72** [propelorm/Propel2#680]
Currently, after defining our connections under `propel.database.connections` section, we must specify which ones we want to use at runtime and generation time. E.g.

``` yaml
propel:
  database:
    connections:
      MyConnection
        adapter: sqlite
        classname:
        dsn: "sqlite::memory:"
        user: 
        password:

  generator:
    defaultConnection: MyConnection
    connections:
      - MyConnection

  runtime:
    defaultConnection: MyConnection
    connections:
      - MyConnection
```

It's repetitive, especially in all those use cases in which we have the same configured connections, both for runtime and build time.
We can make `propel.runtime.connections` and `propel.generator.connections` as optional and automatically populate them with `propel.database.connections`, if they're not defined.
