### ISSUE TITLE
Default Values in config

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#761]
As @cristianoc72 wrote in #668:

> If a property is marked as 'required', you must write it in your configuration file, otherwise Symfony Config Component throws an exception. If you leave its value empty (or null), then Config Component set it to the default. 

I think this is irritating for two reasons. First if I don't want to change from the default behavior I omit my value. Second, if I want a value to be null, I would set it to nothing/null, when now nothing means default value, I have a problem when default is something else.

Basically, my config snippet is very well explaining this:

```
database.connections.myconn:
        dsn: mysql:host=localhost;dbname=bookstore
        classname: 
        user: root
        password:
```

So, classname is just there to be set to default, well, then I can omit it. Password in this case is explicitely set to null.

So, I'd say default values can be omitted from the config and shouldn't be required.
So,
