### ISSUE TITLE
MSSQL addColumns weird behaviour

### ISSUE THREAD

**Issue by BondITSolutions** [propelorm/Propel2#863]
I'm attempting to reverse generate the schema of a MSSQL database. For this purpose I'm using the following yaml file:

```
dbname:
    adapter: mssql
    classname: Propel\Runtime\Connection\ConnectionWrapper
    dsn: "dblib:host=123.456.789.012;dbname=dbname"
    user: username
    password: password
    attributes:
```

However, when I run it, it throws the following error:

```
[Propel\Generator\Exception\EngineException]
Column "" declared twice in table "Status"
```

This error is thrown here:
https://github.com/propelorm/Propel2/blob/master/src/Propel/Generator/Model/Table.php#L499

The table obviously does not contain any real columns without a name ( :-) ). Whenever I delete this table, it simply returns the same error for the next table. The table Status simply is the first on the list it loops through to add columns for.

So I went digging and found that it goes wrong here:
https://github.com/propelorm/Propel2/blob/62859fd0ed3520b7d7afbbdeac113edaf160982b/src/Propel/Generator/Reverse/MssqlSchemaParser.php#L124

```
protected function addColumns(Table $table)
    {
        $dataFetcher = $this->dbh->query("sp_columns '" . $table->getName() . "'");
        foreach ($dataFetcher as $row) {
            $name = $this->cleanDelimitedIdentifiers($row['COLUMN_NAME']);
```

$table->getName() correctly returns the right table name, however when I print $row it contains the following array:

```
Array(
    [0] => My DBname
    [1] => My DBprefix
    [2] => Status
    [3] => uid
    [4] => 4
    [5] => int identity
    etc.
```

The array contains no string indices, hence $row['COLUMN_NAME'] and others will be empty. Why is this?
