### ISSUE TITLE
Confusion between --connection and referring to which connection config to use

### ISSUE THREAD

**Issue by farhanrahman** [propelorm/Propel2#874]
So from the gitter chat earlier today @Celc discovered a case where trying to access a connection config using the flag --connection results in an error. The yaml configuration file looks like this:

````yaml
propel:
    database:
        connections:
            default:
                adapter: mysql
                dsn: mysql:host=localhost;dbname=some_db
                user: root
                password:
                settings:
                    charset: utf8
            staging:
                adapter: mysql
                dsn: mysql:host=staging_host;dbname=some_db
                user: some_username
                password: some_password
                settings:
                    charset: utf8
    generator:
        defaultConnection: default
        connections:
            - default
    runtime:
        defaultConnection: default
        connections:
            - default
````

In AbstractCommand the parseConnection method (https://github.com/propelorm/Propel2/blob/master/src/Propel/Generator/Command/AbstractCommand.php#L118) returns a connection with $name as an empty string.

The problem with this happens in trying to finalize the configuration in Symphony's Processor in here

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Config/Definition/Processor.php#L37

I need to dig into Propel's tree builder to know more about this issue. Either way I think it will be better to distinguish between --connection as a dsn and --connection as a configuration from the yaml/json/* file. Perhaps something like --connection_config=default/staging. Moreover it might be better to put a regexp for the connection to alert the user that the connection format is wrong.
