### ISSUE TITLE
relative path in combination mit command line tool

### ISSUE THREAD

**Issue by inkrement** [propelorm/Propel2#877]
I am using the following directory structure for my project:

```
/public
/public/index.php <--- website home dir/ entry point
/config/config.php <--- generated config
/config/propel.yaml <--- propel config
/src/sql/shop.sql    <--- generated sql file
/shop.db <--- sqlite db
```

And I tried to reference my sqlite db in my ``propel.yaml``with a relative path like this:
```
propel:
  database:
    connections:
      shop:
        adapter: sqlite
        classname: Propel\Runtime\Connection\DebugPDO
        dsn: "sqlite:../shop.db"

```
So the path relative (regarding my index.php) is correct, but when I am using the propel command line tool to generate the database it the parent directory and not the project-directory.
How can I configure the command line tool, or the app to use the same database?

> vendor/bin/propel config:convert --output-dir=config --config-dir=config
> vendor/bin/propel model:build --output-dir=src/domain --config-dir=config
> vendor/bin/propel sql:build --output-dir=src/sql --config-dir=config
> vendor/bin/propel sql:insert --sql-dir=src/sql --config-dir=config

**Comment by marcj** [comment]
You should probably avoid using relative paths and start using `%kernel.root_dir%`:

```yaml
propel:
  database:
    connections:
      shop:
        adapter: sqlite
        classname: Propel\Runtime\Connection\DebugPDO
        dsn: "sqlite:%kernel.root_dir%/shop.db"
```
