### ISSUE TITLE
Unrecognized options under propel.general

### ISSUE THREAD

**Issue by albertodanielojeda** [propelorm/Propel2#994]
Hi everyone. I'm testing Propel's parameters in the configuration file and I got the following error:

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]

Unrecognized options "driver, host, DBName, user, password" under "propel.general"
```

I don't know why, I followed Propel's documentation for configuration files.

Here's my ```propel.yaml```

```
propel:
  general:
      driver: pgsql
      host: localhost
      DBName: myDB
      user: someuser
      password: somepassword
      
  database:
      connections:
          bookstore:
              adapter: %driver%
              classname: Propel\Runtime\Connection\ConnectionWrapper
              dsn: "%driver%:host=%host%;dbname=%DBName%"
              user: %user%
              password: %password%
              attributes:
  runtime:
      defaultConnection: myproyect
      connections:
          - myproyect
  generator:
      defaultConnection: myproyect
      connections:
          - myproyect
```

Any ideas?
